In [12]:
import pandas as pd
#Đọc dữ liệu fale đã được chuẩn hoá
stu_clean = pd.read_csv("data_clean/student_class_clean.csv")
atten_clean = pd.read_csv("data_clean/attendance_log_clean.csv")
classes_clean = pd.read_csv("data_clean/class_schedule_clean.csv")

In [13]:
#tổng số lượt Có mặt / Vắng / Đi muộn / Nghỉ phép theo từng sinh viên
attendance_by_student = (atten_clean.groupby(["student_id", "status"]).size().unstack(fill_value=0))
attendance_by_student

status      có mặt  vắng  đi muộn
student_id
sv001            1     0        0
sv002            0     0        1
sv_003           0     1        0

In [15]:
#Tỷ lệ chuyên cần (Present / Tổng số buổi) theo từng sinh viên
attendance_by_student["attendance_rate"] = (attendance_by_student["có mặt"] /attendance_by_student.sum(axis=1))
attendance_by_student[["attendance_rate"]]

status      attendance_rate
student_id
sv001                   1.0
sv002                   0.0
sv_003                  0.0

In [16]:
#Tính tỷ lệ chuyên cần trung bình theo class_id để so sánh giữa các lớp học phần
attendance_rate_by_class = (atten_clean.groupby("class_id")["status"].apply(lambda x: (x == "có mặt").mean())
                            .reset_index(name="avg_attendance_rate"))
attendance_rate_by_class

  class_id  avg_attendance_rate
0  hp10101                  0.5
1  hp20502                  0.0

In [17]:
#Tính tỷ lệ chuyên cần trung bình theo course_name để đánh giá theo môn học
attendance_rate_by_course = (
    atten_clean
    .merge(classes_clean, on="class_id", how="left")
    .groupby("course_name")["status"]
    .apply(lambda x: (x == "có mặt").mean())
    .reset_index(name="avg_attendance_rate")
)

attendance_rate_by_course

Empty DataFrame
Columns: [course_name, avg_attendance_rate]
Index: []

In [ ]:
attendance_rate_by_course = (
    atten_clean.merge(classes_clean, on="class_id", how="left").groupby("course_name")["status"].apply(lambda x: (x == "có mặt").mean())
    .reset_index(name="avg_attendance_rate"))
attendance_rate_by_course

Empty DataFrame
Columns: [course_name, avg_attendance_rate]
Index: []